// RUN: waveasm-translate %s 2>&1 | FileCheck %s
//
// Test: use_buffer_ops path -- fat_raw_buffer_cast with pending SRD base
// adjustment from reinterpret_cast. Verifies that vector.load/store from
// fat_raw_buffer memrefs correctly propagate the per-workgroup SRD base
// adjustment through the memref.cast -> fat_raw_buffer_cast chain, rather
// than constructing cache-swizzle SRDs.

// CHECK-LABEL: waveasm.program @buffer_ops_test

module {
func.func @buffer_ops_test(%arg0: memref<f16>, %arg1: memref<f32>) {
  %c0 = arith.constant 0 : index
  %c64 = arith.constant 64 : index
  %c128 = arith.constant 128 : index
  %valid_f16 = arith.constant 2147483645 : i64
  %valid_f32 = arith.constant 2147483643 : i64
  %stride_128 = arith.constant 128 : i14
  %stride_64 = arith.constant 64 : i14

  %block_id = gpu.block_id x upper_bound 4
  %thread_id = gpu.thread_id x upper_bound 64

  %wg_row = arith.muli %block_id, %c128 : index
  %th_offset = arith.muli %thread_id, %c128 : index

  // === INPUT: reinterpret_cast -> cast -> fat_raw_buffer_cast -> load ===
  // This is the pattern generated by use_buffer_ops=True for global loads.
  %rc0 = memref.reinterpret_cast %arg0 to
      offset: [%wg_row], sizes: [1073741822], strides: [1]
      : memref<f16> to memref<1073741822xf16, strided<[1], offset: ?>>
  %cast0 = memref.cast %rc0
      : memref<1073741822xf16, strided<[1], offset: ?>>
        to memref<?xf16, strided<[1], offset: ?>>
  %buf0 = amdgpu.fat_raw_buffer_cast %cast0
      validBytes(%valid_f16) cacheSwizzleStride(%stride_128) resetOffset
      : memref<?xf16, strided<[1], offset: ?>>
        to memref<?xf16, #amdgpu.address_space<fat_raw_buffer>>

  // The load SRD should be adjusted with the workgroup offset via SALU:
  //   s_mov_b64 (copy base), v_readfirstlane_b32 (wg offset to SGPR),
  //   s_mul_i32 (byte offset), s_add_u32 + s_addc_u32 (adjust base),
  //   s_mov_b32 (num_records = 0x7FFFFFFE, sentinel-safe max)
  // CHECK: s_mov_b64 s[{{[0-9]+}}:{{[0-9]+}}], s[{{[0-9]+}}:{{[0-9]+}}]
  // CHECK: waveasm.v_readfirstlane_b32
  // CHECK: waveasm.s_mul_hi_u32
  // CHECK: waveasm.s_mul_i32
  // CHECK: waveasm.s_add_u32
  // CHECK: waveasm.s_addc_u32
  // CHECK: s_mov_b32 s{{[0-9]+}}, 0x7FFFFFFE
  // CHECK: s_mov_b32 s{{[0-9]+}}, 0x20000
  // CHECK: waveasm.buffer_load_dwordx2
  %loaded = vector.load %buf0[%th_offset]
      : memref<?xf16, #amdgpu.address_space<fat_raw_buffer>>, vector<4xf16>

  // === OUTPUT: reinterpret_cast -> cast -> fat_raw_buffer_cast -> store ===
  %wg_out = arith.muli %block_id, %c64 : index
  %rc1 = memref.reinterpret_cast %arg1 to
      offset: [%wg_out], sizes: [536870910], strides: [1]
      : memref<f32> to memref<536870910xf32, strided<[1], offset: ?>>
  %cast1 = memref.cast %rc1
      : memref<536870910xf32, strided<[1], offset: ?>>
        to memref<?xf32, strided<[1], offset: ?>>
  %buf1 = amdgpu.fat_raw_buffer_cast %cast1
      validBytes(%valid_f32) cacheSwizzleStride(%stride_64) resetOffset
      : memref<?xf32, strided<[1], offset: ?>>
        to memref<?xf32, #amdgpu.address_space<fat_raw_buffer>>

  %elem = vector.extract_strided_slice %loaded
      {offsets = [0], sizes = [1], strides = [1]}
      : vector<4xf16> to vector<1xf16>
  %ext = arith.extf %elem : vector<1xf16> to vector<1xf32>

  // The store SRD should also be adjusted, with sentinel-safe max num_records
  // CHECK: s_mov_b64 s[{{[0-9]+}}:{{[0-9]+}}], s[{{[0-9]+}}:{{[0-9]+}}]
  // CHECK: waveasm.v_readfirstlane_b32
  // CHECK: waveasm.s_mul_hi_u32
  // CHECK: waveasm.s_mul_i32
  // CHECK: waveasm.s_add_u32
  // CHECK: waveasm.s_addc_u32
  // CHECK: s_mov_b32 s{{[0-9]+}}, 0x7FFFFFFE
  // CHECK: s_mov_b32 s{{[0-9]+}}, 0x20000
  // CHECK: waveasm.buffer_store_dword
  vector.store %ext, %buf1[%thread_id]
      : memref<?xf32, #amdgpu.address_space<fat_raw_buffer>>, vector<1xf32>

  return
}
}
