// Copyright 2025 The Wave Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef WATER_DIALECT_WAVE_WAVEINTERFACES
#define WATER_DIALECT_WAVE_WAVEINTERFACES

include "mlir/IR/OpBase.td"

def HasWaveIndexMapping : NativeOpTrait<"HasWaveIndexMapping"> {
  let cppNamespace = "::wave";
}

#endif // WATER_DIALECT_WAVE_WAVEINTERFACES
